config/routes.rb
SEG3::Application.routes.draw do
  root 'questionnaires#index'

  resources :questionnaires do
    resources :questions, only: [:show, :edit, :create, :update, :destroy]
  end
  
  resources :questions do
    resources :question_options, only: [:edit, :create, :update, :destroy]
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :questionnaire
  has_many :question_options

  @supported_types = ["Multiple Choice", "Scale", "Free Text"]
  
  validates :questionnaire_id, presence: true
  validates :question_type, inclusion: { in: @supported_types, message: "Not a valid question type!" }

end

app/models/question_option.rb
class QuestionOption < ActiveRecord::Base
  belongs_to :question
end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  has_many :questions, include: [:question_options]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  # GET /questionnaires
  # GET /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  # GET /questionnaires/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @questionnaire.to_json(:include => :questions)}
    end
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  # POST /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully created.' }
        format.json { render action: 'show', status: :created, location: @questionnaire }
      else
        format.html { render action: 'new' }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1
  # PATCH/PUT /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1
  # DELETE /questionnaires/1.json
  def destroy
    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to questionnaires_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionnaire_params
      params.require(:questionnaire).permit(:title, :description)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :update, :destroy]

  def show
    render json: @question.to_json(include: :question_options), status: :ok
  end

  def create
    @question = Question.new(question_params)
    @question.questionnaire_id = params[:questionnaire_id]

    @question.save
    respond_to do |format|
      format.js
    end
  end

  def update
    if @question.update
      render json: @question.to_json, status: :ok
    else
      render json: @question.errors.to_json, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy

    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question 
      @question = Question.find(params[:id])
    end
    
    def question_params
      params.require(:question).permit(:title, :subtext, :questionnaire_id, :question_type, :required)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SEG3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <br>

  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Group E", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">Home</a></li>
            <li><a href="#">Surveys</a></li>
            <li><a href="#">Patients</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Profile</a></li>
                <li><a href="#">Settings</a></li>
                <li class="divider"></li>
                <li><a href="#">Logout</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->

      </div><!-- /.container-fluid -->
    </nav>
  </div>

  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>

app/views/questionnaires/_form.html.erb
<%= form_for(@questionnaire) do |f| %>
  <% if @questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
      <% @questionnaire.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questionnaires/edit.html.erb
<h1>Editing questionnaire</h1>

<%= render 'form' %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questionnaires/index.html.erb
<h1>Listing questionnaires</h1>

<div class="row">
  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @questionnaires.each do |questionnaire| %>
          <tr>
            <td><%= questionnaire.title %></td>
            <td><%= questionnaire.description %></td>
            <td><%= link_to 'Show', questionnaire %> | <%= link_to 'Edit', edit_questionnaire_path(questionnaire) %> | <%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Questionnaire', new_questionnaire_path %>

app/views/questionnaires/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New questionnaire</h1>
    <%= render 'form' %>
    <%= link_to 'Back', questionnaires_path %>
  </div>
</div>

app/views/questionnaires/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-md-6'>
    <h1><%= @questionnaire.title %></h1>

    <p>
      <strong>Description:</strong>
      <%= @questionnaire.description %>
    </p>
  </div>
  <div class='col-md-6'>
  </div>
</div>

<br>

<div id='questions-list'>
  <% @questionnaire.questions.each do |question| %>
    <%= render question %> 
  <% end %>
</div>

<hr>

<div class='row'>
  <div class='col-md-12'>
    <h4>New Question</h4>
    <%= form_for [@questionnaire, Question.new], method: "post", remote: true do |f|  %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>

      <div class="form-group">
        <%= f.label :subtext %>
        <%= f.text_field :subtext %>
      </div>

      <div class="form-group">
        <%= f.label :required %>
        <%= f.check_box :required %>
      </div>
      
      <div class="form-group">
        <%= f.label :question_type %>
        <%= f.select :question_type, [["Scale", "Scale"], ["Free Text", "Free Text"]] %>
      </div>

      <div class="form-group">
        <%= f.submit "Create Question" %>
      </div>
    <% end %>
  </div>
</div>
  

<%= link_to 'Edit', edit_questionnaire_path(@questionnaire) %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questions/_question.html.erb
<%= div_for question do %> 
  <div class='row'>
    <div class='col-md-6'>
      <div class='panel panel-default'>
        <div class='panel-heading'>
          <p class='lead'><%= question.title %></p>
          <p><small><%= question.subtext %></small></p>
        </div> 
        <div class='panel-body'>

          <!-- Scale question -->
          <% if question.question_type == "Scale" %>

            <form class='form-inline' role='form'>
              <div class="form-group">
                <% question.question_options.each do |option| %>
                  <label>
                    <input type="radio" name="radio-<%= question.id %>" value="<%= option.text %>">
                      <%= option.text %>
                    </input>
                  </label>
                <% end %>
              </div>
            </form>
          <!-- Free Text question -->
          <% elsif question.question_type == "Free Text" %>

            <form class='form-inline' role='form'>
              <div class="form-group">
                  <label>
                    <input type="text">
                  </label>
              </div>
            </form>
          
          <% end %>
        
          <%= link_to "Delete Question", question_path(question), method: :delete, remote: true %>
    
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/create.js.erb
<% if @question.new_record? %>
  console.log("<%= @question.errors.to_json %>");
<% else %>
  $("div#questions-list").append("<%= escape_javascript(render @question) %>").fadeIn();
  $("form#new_question").get(0).reset();
<% end %>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/destroy.js.erb
console.log("<%= dom_id(@question) %>");
$("#<%= dom_id(@question) %>").fadeOut();

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>